version: "3.9"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "./data/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefiknet

networks:
  traefiknet:
    name: traefiknet
    driver: bridge
